repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=80]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
      - id: requirements-txt-fixer
      - id: pretty-format-json
      - id: debug-statements
        stages: [push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.720"
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: "1.6.2"
    hooks:
      - id: bandit
        args: [--ini=./.bandit]

  - repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        entry: isort
        types: [python]

      - id: pylint
        name: PyLint
        language: python
        entry: pylint
        types: [python]
        additional_dependencies: [toml]
        args: [--reports=n, --output-format=colorized]

      - id: pytest
        name: PyTest
        language: python
        entry: pytest
        types: [python]
        pass_filenames: false
        stages: [push]
        args: [--cov={{ cookiecutter.project_slug }}, --cov-fail-under=80]
